  theme = "stack"
  baseURL = "https://varsha256.github.io/"
  [params]
    avatar = "img/avatar.png"
    customCSS = ["css/custom.css"]

  [params.sidebar]
    emoji = "ðŸ‘‹"
    subtitle = "Quality Engineer | AI in Testing | Automation"
    
    [params.sidebar.avatar]
      enabled = true
      local = true
      src = "img/avatar.png"
[params.homepage]
  layout = "list"

[[params.homepage.sections]]
  section = "about"

  
